// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main #(
 parameter v3edc8f = 1
) (
 input v2df548,
 input vfc5827,
 output v8606be,
 output v53f795,
 output v7b8005,
 output v97033c,
 output v6dd305
);
 localparam p64 = v3edc8f;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w65;
 wire w66;
 wire w67;
 wire w68;
 wire w69;
 wire w70;
 wire w71;
 wire w72;
 wire w73;
 wire w74;
 wire w75;
 wire w76;
 wire w77;
 assign w63 = v2df548;
 assign v8606be = w65;
 assign w70 = vfc5827;
 assign w71 = vfc5827;
 assign v6dd305 = w74;
 assign v97033c = w75;
 assign v7b8005 = w76;
 assign v53f795 = w77;
 assign w32 = w31;
 assign w33 = w31;
 assign w33 = w32;
 assign w34 = w31;
 assign w34 = w32;
 assign w34 = w33;
 assign w35 = w31;
 assign w35 = w32;
 assign w35 = w33;
 assign w35 = w34;
 assign w36 = w31;
 assign w36 = w32;
 assign w36 = w33;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w31;
 assign w37 = w32;
 assign w37 = w33;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w31;
 assign w38 = w32;
 assign w38 = w33;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 assign w39 = w31;
 assign w39 = w32;
 assign w39 = w33;
 assign w39 = w34;
 assign w39 = w35;
 assign w39 = w36;
 assign w39 = w37;
 assign w39 = w38;
 assign w40 = w31;
 assign w40 = w32;
 assign w40 = w33;
 assign w40 = w34;
 assign w40 = w35;
 assign w40 = w36;
 assign w40 = w37;
 assign w40 = w38;
 assign w40 = w39;
 assign w41 = w31;
 assign w41 = w32;
 assign w41 = w33;
 assign w41 = w34;
 assign w41 = w35;
 assign w41 = w36;
 assign w41 = w37;
 assign w41 = w38;
 assign w41 = w39;
 assign w41 = w40;
 assign w42 = w31;
 assign w42 = w32;
 assign w42 = w33;
 assign w42 = w34;
 assign w42 = w35;
 assign w42 = w36;
 assign w42 = w37;
 assign w42 = w38;
 assign w42 = w39;
 assign w42 = w40;
 assign w42 = w41;
 assign w43 = w31;
 assign w43 = w32;
 assign w43 = w33;
 assign w43 = w34;
 assign w43 = w35;
 assign w43 = w36;
 assign w43 = w37;
 assign w43 = w38;
 assign w43 = w39;
 assign w43 = w40;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w31;
 assign w44 = w32;
 assign w44 = w33;
 assign w44 = w34;
 assign w44 = w35;
 assign w44 = w36;
 assign w44 = w37;
 assign w44 = w38;
 assign w44 = w39;
 assign w44 = w40;
 assign w44 = w41;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w31;
 assign w45 = w32;
 assign w45 = w33;
 assign w45 = w34;
 assign w45 = w35;
 assign w45 = w36;
 assign w45 = w37;
 assign w45 = w38;
 assign w45 = w39;
 assign w45 = w40;
 assign w45 = w41;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 assign w46 = w31;
 assign w46 = w32;
 assign w46 = w33;
 assign w46 = w34;
 assign w46 = w35;
 assign w46 = w36;
 assign w46 = w37;
 assign w46 = w38;
 assign w46 = w39;
 assign w46 = w40;
 assign w46 = w41;
 assign w46 = w42;
 assign w46 = w43;
 assign w46 = w44;
 assign w46 = w45;
 assign w47 = w31;
 assign w47 = w32;
 assign w47 = w33;
 assign w47 = w34;
 assign w47 = w35;
 assign w47 = w36;
 assign w47 = w37;
 assign w47 = w38;
 assign w47 = w39;
 assign w47 = w40;
 assign w47 = w41;
 assign w47 = w42;
 assign w47 = w43;
 assign w47 = w44;
 assign w47 = w45;
 assign w47 = w46;
 assign w48 = w31;
 assign w48 = w32;
 assign w48 = w33;
 assign w48 = w34;
 assign w48 = w35;
 assign w48 = w36;
 assign w48 = w37;
 assign w48 = w38;
 assign w48 = w39;
 assign w48 = w40;
 assign w48 = w41;
 assign w48 = w42;
 assign w48 = w43;
 assign w48 = w44;
 assign w48 = w45;
 assign w48 = w46;
 assign w48 = w47;
 assign w49 = w31;
 assign w49 = w32;
 assign w49 = w33;
 assign w49 = w34;
 assign w49 = w35;
 assign w49 = w36;
 assign w49 = w37;
 assign w49 = w38;
 assign w49 = w39;
 assign w49 = w40;
 assign w49 = w41;
 assign w49 = w42;
 assign w49 = w43;
 assign w49 = w44;
 assign w49 = w45;
 assign w49 = w46;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w31;
 assign w50 = w32;
 assign w50 = w33;
 assign w50 = w34;
 assign w50 = w35;
 assign w50 = w36;
 assign w50 = w37;
 assign w50 = w38;
 assign w50 = w39;
 assign w50 = w40;
 assign w50 = w41;
 assign w50 = w42;
 assign w50 = w43;
 assign w50 = w44;
 assign w50 = w45;
 assign w50 = w46;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w31;
 assign w51 = w32;
 assign w51 = w33;
 assign w51 = w34;
 assign w51 = w35;
 assign w51 = w36;
 assign w51 = w37;
 assign w51 = w38;
 assign w51 = w39;
 assign w51 = w40;
 assign w51 = w41;
 assign w51 = w42;
 assign w51 = w43;
 assign w51 = w44;
 assign w51 = w45;
 assign w51 = w46;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w31;
 assign w52 = w32;
 assign w52 = w33;
 assign w52 = w34;
 assign w52 = w35;
 assign w52 = w36;
 assign w52 = w37;
 assign w52 = w38;
 assign w52 = w39;
 assign w52 = w40;
 assign w52 = w41;
 assign w52 = w42;
 assign w52 = w43;
 assign w52 = w44;
 assign w52 = w45;
 assign w52 = w46;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w31;
 assign w53 = w32;
 assign w53 = w33;
 assign w53 = w34;
 assign w53 = w35;
 assign w53 = w36;
 assign w53 = w37;
 assign w53 = w38;
 assign w53 = w39;
 assign w53 = w40;
 assign w53 = w41;
 assign w53 = w42;
 assign w53 = w43;
 assign w53 = w44;
 assign w53 = w45;
 assign w53 = w46;
 assign w53 = w47;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 assign w54 = w31;
 assign w54 = w32;
 assign w54 = w33;
 assign w54 = w34;
 assign w54 = w35;
 assign w54 = w36;
 assign w54 = w37;
 assign w54 = w38;
 assign w54 = w39;
 assign w54 = w40;
 assign w54 = w41;
 assign w54 = w42;
 assign w54 = w43;
 assign w54 = w44;
 assign w54 = w45;
 assign w54 = w46;
 assign w54 = w47;
 assign w54 = w48;
 assign w54 = w49;
 assign w54 = w50;
 assign w54 = w51;
 assign w54 = w52;
 assign w54 = w53;
 assign w55 = w31;
 assign w55 = w32;
 assign w55 = w33;
 assign w55 = w34;
 assign w55 = w35;
 assign w55 = w36;
 assign w55 = w37;
 assign w55 = w38;
 assign w55 = w39;
 assign w55 = w40;
 assign w55 = w41;
 assign w55 = w42;
 assign w55 = w43;
 assign w55 = w44;
 assign w55 = w45;
 assign w55 = w46;
 assign w55 = w47;
 assign w55 = w48;
 assign w55 = w49;
 assign w55 = w50;
 assign w55 = w51;
 assign w55 = w52;
 assign w55 = w53;
 assign w55 = w54;
 assign w56 = w31;
 assign w56 = w32;
 assign w56 = w33;
 assign w56 = w34;
 assign w56 = w35;
 assign w56 = w36;
 assign w56 = w37;
 assign w56 = w38;
 assign w56 = w39;
 assign w56 = w40;
 assign w56 = w41;
 assign w56 = w42;
 assign w56 = w43;
 assign w56 = w44;
 assign w56 = w45;
 assign w56 = w46;
 assign w56 = w47;
 assign w56 = w48;
 assign w56 = w49;
 assign w56 = w50;
 assign w56 = w51;
 assign w56 = w52;
 assign w56 = w53;
 assign w56 = w54;
 assign w56 = w55;
 assign w57 = w31;
 assign w57 = w32;
 assign w57 = w33;
 assign w57 = w34;
 assign w57 = w35;
 assign w57 = w36;
 assign w57 = w37;
 assign w57 = w38;
 assign w57 = w39;
 assign w57 = w40;
 assign w57 = w41;
 assign w57 = w42;
 assign w57 = w43;
 assign w57 = w44;
 assign w57 = w45;
 assign w57 = w46;
 assign w57 = w47;
 assign w57 = w48;
 assign w57 = w49;
 assign w57 = w50;
 assign w57 = w51;
 assign w57 = w52;
 assign w57 = w53;
 assign w57 = w54;
 assign w57 = w55;
 assign w57 = w56;
 assign w58 = w31;
 assign w58 = w32;
 assign w58 = w33;
 assign w58 = w34;
 assign w58 = w35;
 assign w58 = w36;
 assign w58 = w37;
 assign w58 = w38;
 assign w58 = w39;
 assign w58 = w40;
 assign w58 = w41;
 assign w58 = w42;
 assign w58 = w43;
 assign w58 = w44;
 assign w58 = w45;
 assign w58 = w46;
 assign w58 = w47;
 assign w58 = w48;
 assign w58 = w49;
 assign w58 = w50;
 assign w58 = w51;
 assign w58 = w52;
 assign w58 = w53;
 assign w58 = w54;
 assign w58 = w55;
 assign w58 = w56;
 assign w58 = w57;
 assign w59 = w31;
 assign w59 = w32;
 assign w59 = w33;
 assign w59 = w34;
 assign w59 = w35;
 assign w59 = w36;
 assign w59 = w37;
 assign w59 = w38;
 assign w59 = w39;
 assign w59 = w40;
 assign w59 = w41;
 assign w59 = w42;
 assign w59 = w43;
 assign w59 = w44;
 assign w59 = w45;
 assign w59 = w46;
 assign w59 = w47;
 assign w59 = w48;
 assign w59 = w49;
 assign w59 = w50;
 assign w59 = w51;
 assign w59 = w52;
 assign w59 = w53;
 assign w59 = w54;
 assign w59 = w55;
 assign w59 = w56;
 assign w59 = w57;
 assign w59 = w58;
 assign w60 = w31;
 assign w60 = w32;
 assign w60 = w33;
 assign w60 = w34;
 assign w60 = w35;
 assign w60 = w36;
 assign w60 = w37;
 assign w60 = w38;
 assign w60 = w39;
 assign w60 = w40;
 assign w60 = w41;
 assign w60 = w42;
 assign w60 = w43;
 assign w60 = w44;
 assign w60 = w45;
 assign w60 = w46;
 assign w60 = w47;
 assign w60 = w48;
 assign w60 = w49;
 assign w60 = w50;
 assign w60 = w51;
 assign w60 = w52;
 assign w60 = w53;
 assign w60 = w54;
 assign w60 = w55;
 assign w60 = w56;
 assign w60 = w57;
 assign w60 = w58;
 assign w60 = w59;
 assign w61 = w31;
 assign w61 = w32;
 assign w61 = w33;
 assign w61 = w34;
 assign w61 = w35;
 assign w61 = w36;
 assign w61 = w37;
 assign w61 = w38;
 assign w61 = w39;
 assign w61 = w40;
 assign w61 = w41;
 assign w61 = w42;
 assign w61 = w43;
 assign w61 = w44;
 assign w61 = w45;
 assign w61 = w46;
 assign w61 = w47;
 assign w61 = w48;
 assign w61 = w49;
 assign w61 = w50;
 assign w61 = w51;
 assign w61 = w52;
 assign w61 = w53;
 assign w61 = w54;
 assign w61 = w55;
 assign w61 = w56;
 assign w61 = w57;
 assign w61 = w58;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w31;
 assign w62 = w32;
 assign w62 = w33;
 assign w62 = w34;
 assign w62 = w35;
 assign w62 = w36;
 assign w62 = w37;
 assign w62 = w38;
 assign w62 = w39;
 assign w62 = w40;
 assign w62 = w41;
 assign w62 = w42;
 assign w62 = w43;
 assign w62 = w44;
 assign w62 = w45;
 assign w62 = w46;
 assign w62 = w47;
 assign w62 = w48;
 assign w62 = w49;
 assign w62 = w50;
 assign w62 = w51;
 assign w62 = w52;
 assign w62 = w53;
 assign w62 = w54;
 assign w62 = w55;
 assign w62 = w56;
 assign w62 = w57;
 assign w62 = w58;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w66 = w1;
 assign w67 = w5;
 assign w68 = w6;
 assign w69 = w65;
 assign w71 = w70;
 assign w74 = w27;
 assign w75 = w28;
 assign w76 = w29;
 assign w77 = w30;
 v6a5074 #(
  .v100e1b(p64)
 ) vf5b573 (
  .v2efea4(w31),
  .v0daa9e(w63)
 );
 v8b89a5 v334f63 (
  .vc24d9f(w0),
  .vb55943(w31),
  .vef4cea(w72)
 );
 v8b89a5 v25455a (
  .vef4cea(w0),
  .vc24d9f(w1),
  .vb55943(w32)
 );
 v8b89a5 vdfbd4a (
  .vef4cea(w1),
  .vc24d9f(w2),
  .vb55943(w49)
 );
 v8b89a5 v2fc486 (
  .vef4cea(w2),
  .vc24d9f(w3),
  .vb55943(w33)
 );
 v8b89a5 vfecff5 (
  .vef4cea(w3),
  .vc24d9f(w4),
  .vb55943(w43)
 );
 v8b89a5 vf11cf2 (
  .vef4cea(w4),
  .vc24d9f(w5),
  .vb55943(w51)
 );
 v8b89a5 v75084e (
  .vef4cea(w5),
  .vc24d9f(w6),
  .vb55943(w55)
 );
 v8b89a5 vbceabf (
  .vef4cea(w6),
  .vc24d9f(w7),
  .vb55943(w59)
 );
 v8b89a5 va40faa (
  .vef4cea(w7),
  .vc24d9f(w8),
  .vb55943(w34)
 );
 v8b89a5 vda08c2 (
  .vef4cea(w8),
  .vc24d9f(w9),
  .vb55943(w37)
 );
 v8b89a5 v069578 (
  .vef4cea(w9),
  .vc24d9f(w10),
  .vb55943(w40)
 );
 v8b89a5 vc95bc0 (
  .vef4cea(w10),
  .vc24d9f(w11),
  .vb55943(w45)
 );
 v8b89a5 v03bdb4 (
  .vef4cea(w11),
  .vc24d9f(w12),
  .vb55943(w44)
 );
 v8b89a5 v4ab5ff (
  .vef4cea(w12),
  .vc24d9f(w13),
  .vb55943(w52)
 );
 v8b89a5 vf3107e (
  .vef4cea(w13),
  .vc24d9f(w14),
  .vb55943(w56)
 );
 v8b89a5 vae460b (
  .vef4cea(w14),
  .vc24d9f(w15),
  .vb55943(w60)
 );
 v8b89a5 vabcabb (
  .vef4cea(w15),
  .vc24d9f(w16),
  .vb55943(w35)
 );
 v8b89a5 v6bf045 (
  .vef4cea(w16),
  .vc24d9f(w17),
  .vb55943(w38)
 );
 v8b89a5 v6f1945 (
  .vef4cea(w17),
  .vc24d9f(w18),
  .vb55943(w41)
 );
 v8b89a5 v532258 (
  .vef4cea(w18),
  .vc24d9f(w19),
  .vb55943(w46)
 );
 v8b89a5 v213c76 (
  .vef4cea(w19),
  .vc24d9f(w20),
  .vb55943(w48)
 );
 v8b89a5 v970893 (
  .vef4cea(w20),
  .vc24d9f(w21),
  .vb55943(w53)
 );
 v8b89a5 vd66bde (
  .vef4cea(w21),
  .vc24d9f(w22),
  .vb55943(w57)
 );
 v8b89a5 v8fdb5e (
  .vef4cea(w22),
  .vc24d9f(w23),
  .vb55943(w61)
 );
 v8b89a5 v181834 (
  .vef4cea(w23),
  .vc24d9f(w24),
  .vb55943(w36)
 );
 v8b89a5 vbc019a (
  .vef4cea(w24),
  .vc24d9f(w25),
  .vb55943(w39)
 );
 v8b89a5 ve0b067 (
  .vef4cea(w25),
  .vc24d9f(w26),
  .vb55943(w42)
 );
 v8b89a5 v82b6ca (
  .vef4cea(w26),
  .vc24d9f(w27),
  .vb55943(w47)
 );
 v8b89a5 vedbe57 (
  .vef4cea(w27),
  .vc24d9f(w28),
  .vb55943(w50)
 );
 v8b89a5 vce88d3 (
  .vef4cea(w28),
  .vc24d9f(w29),
  .vb55943(w54)
 );
 v8b89a5 va723c2 (
  .vef4cea(w29),
  .vc24d9f(w30),
  .vb55943(w58)
 );
 v8b89a5 v7de6de (
  .vef4cea(w30),
  .vb55943(w62),
  .vc24d9f(w65)
 );
 vd137c4 v95e30e (
  .v984fbd(w66),
  .v758f00(w67),
  .va90145(w68),
  .v9b4388(w69),
  .vbac23b(w73)
 );
 v2d00dc va7c3b0 (
  .v675419(w70),
  .v9a9c84(w71),
  .v741632(w72),
  .v765971(w73)
 );
endmodule

//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module v8b89a5 (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v8b89a5_v526aa2 v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Flip-flop D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Delay flip-flop
//---------------------------------------------------

module v8b89a5_v526aa2 (
 input clk,
 input d,
 output q
);
 // D flip-flop
 
 reg q = 1'b0;
 
 always @(posedge clk)
 begin
   q <= d;
 end
 
 
endmodule
//---- Top entity
module vd137c4 (
 input v984fbd,
 input v758f00,
 input va90145,
 input v9b4388,
 output vbac23b
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w2 = v984fbd;
 assign vbac23b = w3;
 assign w4 = v758f00;
 assign w5 = va90145;
 assign w6 = v9b4388;
 ve9ceb2 vb797d4 (
  .vcbab45(w0),
  .v0e28cb(w2),
  .v3ca442(w4)
 );
 ve9ceb2 vc9fa36 (
  .vcbab45(w1),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
 ve9ceb2 v0c0a1b (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w3)
 );
endmodule

//---- Top entity
module ve9ceb2 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 ve9ceb2_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR logic gate
//---------------------------------------------------

module ve9ceb2_vf4938a (
 input a,
 input b,
 output c
);
 // XOR logic gate
 
 assign c = a ^ b;
endmodule
//---- Top entity
module v2d00dc (
 input v765971,
 input v9a9c84,
 input v675419,
 output v741632
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v741632 = w0;
 assign w1 = v765971;
 assign w2 = v9a9c84;
 assign w3 = v675419;
 v2d00dc_v7f68b8 v7f68b8 (
  .o(w0),
  .in0(w1),
  .in1(w2),
  .sel0(w3)
 );
endmodule

//---------------------------------------------------
//-- Mux 2:1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Multiplexer 2:1
//---------------------------------------------------

module v2d00dc_v7f68b8 (
 input in0,
 input in1,
 input sel0,
 output o
);
 reg _o;
 
 always @(*) begin
     case(sel0)
         0: _o = in0;
         1: _o = in1;
         default: _o = in0;
     endcase
 end
 
 assign o = _o;
endmodule
